#! /bin/sh
# 
# Cumulus Firewall 
# Copyright (C) 2000  Øyvind Jelstad, Cumulus IT AS
# 
# $Id: ipsec_updown,v 1.4 2003/03/18 22:25:29 oyvind Exp $


#Debug:
#echo "Parameters:( $* )"  >&2
#echo "$0: $PLUTO_VERB:$1" >&2

# check interface version
case "$PLUTO_VERSION" in
1.0)	;;
*)	echo "$0: unknown interface version \`$PLUTO_VERSION'" >&2
	exit 2
	;;
esac

# check parameter(s)
case "$*" in
'')	;;
ipfwadm)	# caused by (left/right)firewall=yes
	;;
*)	echo "$0: unknown parameter \`$1'" >&2
	exit 2
	;;
esac

# utility functions for route manipulation
# Meddling with this stuff should never be necessary and is most unwise.
uproute() {
	route add -net $PLUTO_PEER_CLIENT_NET netmask $PLUTO_PEER_CLIENT_MASK \
		dev $PLUTO_INTERFACE gw $PLUTO_NEXT_HOP
}
downroute() {
	route del -net $PLUTO_PEER_CLIENT_NET netmask $PLUTO_PEER_CLIENT_MASK \
		dev $PLUTO_INTERFACE gw $PLUTO_NEXT_HOP
}



# the big choice
case "$PLUTO_VERB:$1" in
prepare-host:*|prepare-client:*)
	# delete possibly-existing route (preliminary to adding a route)
	oops="`route del -net $PLUTO_PEER_CLIENT_NET \
					netmask $PLUTO_PEER_CLIENT_MASK 2>&1`"
	status="$?"
	if test " $oops" = " " -a " $status" != " 0"
	then
		oops="silent error in route command, exit status $status"
	fi
	case "$oops" in
	'SIOCDELRT: No such process')
		# This is what route (currently -- not documented!) gives
		# for "could not find such a route".
		status=0
		;;
	esac
	exit $status
	;;
route-host:*|route-client:*)
	# connection to this host or client being routed
	uproute
	
      iptables -I OUTPUT -j ACCEPT \
         -s $PLUTO_ME/32 \
         -d $PLUTO_PEER/32 500 -p udp 
	 
      iptables -I OUTPUT -j LOG  --log-prefix "$CFW:IPSEC:ACCEPT RULE=FW " \
         -s $PLUTO_ME/32 \
         -d $PLUTO_PEER/32 500 -p udp 
	 


        ;;
unroute-host:*|unroute-client:*)
	# connection to this host or client being unrouted
	downroute
	
      iptables -D OUTPUT -j ACCEPT \
         -s $PLUTO_ME/32 \
         -d $PLUTO_PEER/32 500 -p udp 
	 
      iptables -D OUTPUT -j LOG  --log-prefix "$CFW:IPSEC:ACCEPT RULE=FW " \
         -s $PLUTO_ME/32 \
         -d $PLUTO_PEER/32 500 -p udp 

	
	;;
up-host:*|up-client:*)
      # connection to this host coming up
	 
      iptables -I OUTPUT -j ACCEPT \
         -s $PLUTO_ME/32 \
         -d $PLUTO_PEER/32 -p 50 
	 
      iptables -I OUTPUT -j LOG  --log-prefix "$CFW:IPSEC:ACCEPT RULE=FW " \
         -s $PLUTO_ME/32 \
         -d $PLUTO_PEER/32 -p 50 
	 

      ;;

down-host:*|down-client:*)
      # connection to this host going down
	 
      iptables -D OUTPUT -j ACCEPT \
         -s $PLUTO_ME/32 \
         -d $PLUTO_PEER/32 -p 50 
	 
      iptables -D OUTPUT -j LOG  --log-prefix "$CFW:IPSEC:ACCEPT RULE=FW " \
         -s $PLUTO_ME/32 \
         -d $PLUTO_PEER/32 -p 50 
	 

    ;;


*)	echo "$0: unknown verb \`$PLUTO_VERB' or parameter \`$1'" >&2
	exit 1
	;;
esac

